# Generated by Django 4.0.4 on 2022-07-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='products_images/'),
        ),
    ]
