# Generated by Django 4.0.4 on 2022-07-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_productinbasket_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinbasket',
            name='user_id',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
    ]
