# Generated by Django 4.0.4 on 2022-07-10 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0011_delete_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='rest_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='rest_images/'),
        ),
    ]
