# Generated by Django 4.0.4 on 2022-07-11 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0012_restaurant_rest_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='courier_phone',
            field=models.CharField(blank=True, default=None, max_length=24, null=True, verbose_name='Номер курьера'),
        ),
    ]
