# Generated by Django 4.0.4 on 2022-07-14 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0013_alter_courier_courier_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_phone',
        ),
    ]
